# Generated by Django 4.0.6 on 2022-08-01 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrupoFamiliar', '0002_familia_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2022, 7, 31, 22, 55, 10, 765640)),
        ),
    ]
