# Generated by Django 4.0.6 on 2022-08-01 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrupoFamiliar', '0003_alter_familia_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='parentesco',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2022, 7, 31, 22, 57, 40, 881430)),
        ),
    ]
